BINANCE_API_BASE_URL = "https://api.binance.com/api"
BINANCE_API_VERSION = "v3"
KUCOIN_API_BASE_URL = "https://api.kucoin.com/api"
KUCOIN_API_VERSION = "v1"
SPOTTER_RUNNING_FREQUENCY = 60
SUPPORTED_STABLECOINS = ("BUSD", "USDC", "USDT")